language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"  
# command to install dependencies
install:
  - pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install -r requires.txt
# command to run tests
script:
  - pytest